### ISSUE TITLE
作者你好，引入后未知报错，求解！！

### ISSUE THREAD

**Issue by wjl57713** [elvinzhu/techarts#11]
Module parse failed: Unexpected token (35:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const canvasId = this.getCanvasId();
|     return (
>       <Canvas
|         type="2d"
|         className="techarts-canvas"
 @ ./node_modules/techarts/dist/weapp/index.js 1:0-41 2:15-21
 @ ./node_modules/techarts/dist/index.js
 @ ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib!./src/pages/Device/HistoryData/HistoryData.jsx
 @ ./src/pages/Device/HistoryData/HistoryData.jsx

**Comment by elvinzhu** [comment]
webpack 配置问题，请将js加入babel处理

test: /\.(js|jsx)?$/,

**Comment by elvinzhu** [comment]
稍等，我升级兼容下taro3

**Comment by s5mple** [comment]
> webpack 配置问题，请将js加入babel处理
> 
> test: /.(js|jsx)?$/,

请问一下这段代码加载配置文件的哪里

**Comment by elvinzhu** [comment]
已做兼容。感谢使用
