### ISSUE TITLE
Taro3 无法使用 

### ISSUE THREAD

**Issue by nuts-cake** [elvinzhu/techarts#13]
作者,您好!
  请问如何在Taro3使用.会报错

**Comment by elvinzhu** [comment]
已做兼容，请安装最新版本使用

**Comment by nuts-cake** [comment]
thank&nbsp;you&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elvinzhu/techarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 晚上7:55
收件人:&nbsp;"elvinzhu/techarts"<techarts@noreply.github.com&gt;;
抄送:&nbsp;"1045059784"<1045059784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [elvinzhu/techarts] Taro3 无法使用  (#13)



 已做兼容，请安装最新版本使用
