### ISSUE TITLE
Taro3 微信小程序 Cannot read 'node' of null 报错

### ISSUE THREAD

**Issue by ShawnTu** [elvinzhu/techarts#15]
Hi，您好，

Taro@3.0.7
techarts@3.0.4（最新版本）

微信开发者工具中能出来图表，但有报错，麻烦看一下

![image](https://user-images.githubusercontent.com/11386495/91663773-88356100-eb1d-11ea-8541-ec45dadd6d5c.png)

真机调试出不来图表，而且有报错

![image](https://user-images.githubusercontent.com/11386495/91702794-d42ee700-ebab-11ea-9123-07d86c4b8855.png)

**Comment by elvinzhu** [comment]
抱歉，刚看到issue.    

但是光看你的报错信息无法定位问题，可否按照你的使用场景新建一个代码片段发出来
