### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lzw1996-2020** [elvinzhu/techarts#16]
一点击该组件就报错
![image](https://user-images.githubusercontent.com/51849466/92471039-dd523080-f209-11ea-891d-23a8e8db4002.png)

**Comment by lzw1996-2020** [comment]
master复制上的

**Comment by lzw1996-2020** [comment]
分支

**Comment by elvinzhu** [comment]
俩版本都MAC上跑了一遍，没重现
