### ISSUE TITLE
好像在Taro3中使用Nerv不行，没有显示 

### ISSUE THREAD

**Issue by tiandezhen** [elvinzhu/techarts#19]
Taro 3.0.15,使用Nerv框架，没有显示，如果用Nerv是否需要修改?

**Comment by elvinzhu** [comment]
techeats 使用的是react。如果需要使用 nerv，可以把 react alias 到 nerv 试试

**Comment by tiandezhen** [comment]
这个不太行，还是用的另一个，问题已经解决，可以参考
主要是这个问题Taro2和3的区别，生命周期不一样了
// https://www.jianshu.com/p/eb662191e947
