### ISSUE TITLE
组件无法随页面滚动怎么解决

### ISSUE THREAD

**Issue by marc111** [elvinzhu/techarts#5]
chart组件无法随页面滚动, 一只处于渲染时所在的位置，一滚动就覆盖其它元素

**Comment by elvinzhu** [comment]
附上小程序代码片段，我可以帮你看下。我自己暂时没有遇到这个问题，但是请注意，canvas是原生组件，使用时注意下层级

**Comment by chjish28461** [comment]
我之前也是碰到这个问题，但是后面发现只有开发者工具上有bug，真及时并没有问题
