### ISSUE TITLE
采用分包，但多个页面引用techart，又打包到公用common.js里面去了，主包又变太大了，怎么解决呀

### ISSUE THREAD

**Issue by JQ1123** [elvinzhu/techarts#8]
![image](https://user-images.githubusercontent.com/15795418/86331904-4f435200-bc7c-11ea-82a1-c305085ef611.png)

**Comment by JQ1123** [comment]
压缩一下，好像小了很多

**Comment by JQ1123** [comment]
有没有更好的方法？

**Comment by elvinzhu** [comment]
能否把引用Techart 的页面，放到一个分包里？

**Comment by JQ1123** [comment]
谢谢大佬回复我~~
是把所有引用Techart的页面放在一个分包里面，但是打包的时候，又打到common.js里面去了。
如果两个页面以上用了Techart，common.js就会增加700多k,就算这两个页面都在一个分包中。



jxjq1123@163.com
 
发件人： Zhu Yongyu
发送时间： 2020-07-03 14:39
收件人： elvinzhu/techarts
抄送： Liu Junquan; Author
主题： Re: [elvinzhu/techarts] 采用分包，但多个页面引用techart，又打包到公用common.js里面去了，主包又变太大了，怎么解决呀 (#8)
能否把引用Techart 的页面，放到一个分包里？

**Comment by elvinzhu** [comment]
1. 提到common里面的主要还是 echarts（注意不是techarts），你可以每个页面使用独立的 echarts， 即：不共享 echarts
2. echarts 建议采用自定义构建的方式，只包含自己需要的图标，这样可以极大减少echarts体积

**Comment by JQ1123** [comment]
好的，我试试，感谢
